In [37]:
from tensorflow.keras.preprocessing.text import one_hot

In [38]:
#sent
sent =[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'uderstand the meaning of words',
    'your videos are good'
]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'uderstand the meaning of words',
 'your videos are good']

In [39]:
##define the vocabulary size
voc_size=10000


In [40]:
#one hot Representation
one_hot_repr = [one_hot(word,voc_size)for word in sent]
one_hot_repr

[[3182, 4408, 7788, 7887],
 [3182, 4408, 7788, 7765],
 [3182, 4631, 7788, 5900],
 [109, 9163, 9255, 661, 2649],
 [109, 9163, 9255, 661, 9045],
 [8064, 3182, 7965, 7788, 8583],
 [1695, 7679, 8227, 661]]

In [41]:
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [42]:
import numpy as np

In [43]:
sent_length =8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3182 4408 7788 7887]
 [   0    0    0    0 3182 4408 7788 7765]
 [   0    0    0    0 3182 4631 7788 5900]
 [   0    0    0  109 9163 9255  661 2649]
 [   0    0    0  109 9163 9255  661 9045]
 [   0    0    0 8064 3182 7965 7788 8583]
 [   0    0    0    0 1695 7679 8227  661]]


In [44]:
#feature represntation
dim=10


In [45]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))
model.compile(optimizer='adam', loss='mse')

c:\Python313\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [46]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [48]:
embedded_docs[0]

array([   0,    0,    0,    0, 3182, 4408, 7788, 7887], dtype=int32)